version: '3.8'

services:
  adonis_app:
    container_name: api_reservation
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    env_file:
      - .env
    # volumes:
      # - ./:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: /bin/sh -c "/home/node/app/entrypoint.sh"